### ISSUE TITLE
ResolvePackageNotFound: Error

### ISSUE THREAD

**Issue by ChangQing-SH** [ramintoosi/ROSS#9]
What kind of the OS platform you used? 
I am trying to install with  "conda env create -f environment.yml"
and got the ResolvePackageNotFound: Error. 

also Could you export the conda environment without builds?

**Comment by ramintoosi** [comment]
Hi, I tested on Ubuntu 20.04/22.04 and python 3.9.7
Furthermore, there exist no packages with manual builds. My suggestion is to remove any _NotFound_ packages from yml file and install a compatible version manually based on your OS.

**Comment by jesusdpa1** [comment]
Hi! is it possible to move the installer from conda to a pyproject.toml using poetry? I think it would be easier for distribution across different OS.

something like 

```toml
[tool.poetry]
name = "ross"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aniso8601 = "9.0.1"
astroid = "2.15.3"
cffi = "1.15.1"
charset-normalizer = "2.0.10"
colour = "0.1.5"
coverage = "7.2.7"
cryptography = "39.0.0"
cycler = "0.11.0"
dill = "0.3.6"
exceptiongroup = "1.1.1"
flask-jwt = "0.3.2"
flask-jwt-extended = "3.0.0"
flask-restful = "0.3.8"
flask-sqlalchemy = "2.5.1"
greenlet = "1.1.2"
h5py = "3.6.0"
idna = "3.3"
iniconfig = "2.0.0"
isort = "5.12.0"
joblib = "1.1.0"
kiwisolver = "1.3.2"
lazy-object-proxy = "1.9.0"
matplotlib = "3.4.3"
mccabe = "0.7.0"
nptdms = "1.4.0"
numpy = "1.22.1"
opencv-python = "4.6.0.66"
pillow = "9.0.0"
platformdirs = "3.2.0"
pluggy = "1.0.0"
pycparser = "2.21"
pyjwt = "1.4.2"
pyopengl = "3.1.5"
pyopenssl = "23.0.0"
pyparsing = "3.0.6"
pyqt5 = "5.15.6"
pyqt5-qt5 = "5.15.2"
pyqt5-sip = "12.9.0"
pyqtgraph = "0.13.1"
pytest = "7.3.2"
pytest-cov = "4.1.0"
pytz = "2021.3"
pywavelets = "1.2.0"
pyyawt = "0.1.1"
requests = "2.26.0"
scikit-learn = "1.0.1"
scipy = "1.7.1"
sip = "6.5.0"
sqlalchemy = "1.4.29"
threadpoolctl = "3.0.0"
tomli = "2.0.1"
tomlkit = "0.11.7"
typing-extensions = "4.5.0"
urllib3 = "1.26.8"
wrapt = "1.15.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


```
